(ns exercises.chapter1.exercise1_15)

;Exercise 1.15
; The sine of an angle (specified in radians) can be computed by making use of the approximation sin x ≈ x
;   if x is sufficiently small, and the trigonometric identity
;
;   sin x = 3sin(x/3) − 4sin(x/3)^3
;
; to reduce the size of the argument of sin. (For purposes of this exercise an angle is considered
;   "sufficiently small" if its magnitude is not greater than 0.1 radians.)
;
; These ideas are incorporated in the following procedures:
;
;   (define (cube x) (* x x x))
;   (define (p x) (- (* 3 x) (* 4 (cube x))))
;   (define (sine angle)
;            (if (not (> (abs angle) 0.1))
;              angle
;              (p (sine (/ angle 3.0)))))
;
;a. How many times is the procedure p applied when (sine 12.15) is evaluated?
;b. What is the order of growth in space and number of steps (as a function of a) used by the process generated by the
; sine procedure when (sine a) is evaluated?

(defn abs [x]
  (if (< x 0)
    (- x)
    x))

(defn cube [x]
  (* x x x))

(defn p [x]
  (println "(p" x ")")
  (- (* 3 x)
     (* 4
        (cube x))))

(defn sine [angle]
  (if (not (> (abs angle) 0.1))
    angle
    (p (sine (/ angle 3.0)))))

(sine 12.15)
; => -0.39980345741334

;(p 0.049999999999999996 )
;(p 0.1495 )
;(p 0.4351345505 )
;(p 0.9758465331678772 )
;(p -0.7895631144708228 )

;(sine 12.15)
;   (p (sine (/ 12.15 3.0)))
;   (p (sine 4.05))
;   (p (sine 4.05))
;   (p (p (sine (/ 4.05 3.0))))
;   (p (p (sine 1.3499999999999999)))
;   (p (p (sine 1.3499999999999999)))
;   (p (p (p (sine (/ 1.3499999999999999 3.0)))))
;   (p (p (p (sine 0.44999999999999996))))
;   (p (p (p (p (sine (/ 0.44999999999999996 3.0))))))
;   (p (p (p (p (sine 0.15)))))
;   (p (p (p (p (sine 0.15)))))
;   (p (p (p (p (p (sine (/ 0.15 3.0)))))))
;   (p (p (p (p (p (sine 0.049999999999999996))))))
;   (p (p (p (p (p (sine 0.049999999999999996))))))
;   (p (p (p (p (p 0.049999999999999996)))))
;   (p -0.7895631144708228)
; => -0.39980345741334

;a) 5
;b) a/3 until a ! > 0.1
